### PR TITLE
Update to Elm 0.18

### PR DESCRIPTION
**Pull request by ThomasWeiser**
See Evan's [upgrading guide](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md).

Most changes will be mechanically ones.
Http API changed, will have to adapt.
Also have to wait for our dependencies to be updated.

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
Should be working now. @oliverbarnes please review.

Some notes about the migration:
- Source is a little bit smaller (-21 lines) and a quite bit clearer now.
- Reimplemented most of routing (bigger changes in `elm-lang/navigation`; no more need for `sporto/hop`). IMHO code got easier to understand.
- Also some bigger changes as a result of new `elm-lang/http`. Pulled in `lukewestby/elm-http-builder` and could drop some own helper functions.
- Good Elm experience again: The compiler with its type checking guides reliably and helpfully thru refactorizations like this one. It provides great confidence in the correctness of the changed code.

**Review by oliverbarnes — APPROVED** [review]
👌 looks great, code is easier to understand indeed. thanks!

**Pull request merged**
