### PR TITLE
Implement styling for 0.0.1

### PR DESCRIPTION
**Pull request by ThomasWeiser**
@tnum put on the last touches on https://github.com/oliverbarnes/participate/pull/38 and it's merged 🎉

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
Finished a first iteration of implementing mockup's style with elm-mdl.

It's not a pixel-perfect replication of the @tnum's mockup, but tries to be very close. It surely needs some more tweaks. Some comments:

- Font: Shall we use Roboto everywhere, or use Helvetica/Arial/sans-serif for the text elements (as in the mockup)?
- elm-mdl is sometimes more strict about nesting certain elements than the mockup.
- Some elements should probably be arranged with specific non-mdl CSS code.
    - Doing this already within `.proposal-card-title` (using flexboxes).
    - As far as I can tell mdl's `grid`/`cell` is suitable mainly for page layout, but may be less so within sub elements. E.g. usage of `grid`+`spacer` to distribute content within horizontal space should probably done with some own flexbox-based classes.
    - Ideally, there should be no direct mentions of `mdl-...` classes in our view functions.
- The CSS code needs some clean up. Also, a CSS preprocessor may be worth considering.

@oliverbarnes, @tnum please let me know what you think!

**Comment by ThomasWeiser** [comment]
By the way, there is currently a greater discussion in Elm land about utilizing webcomponents (together with Polymer). This could someday lead to an alternative way of implementing Material Design UIs.

Instead of mdl (and elm-mdl) one would use the [corresponding custom elements](https://beta.webcomponents.org/collection/Polymer/elements) from Polymer's catalog.

Links:
- Main discussion on [elm-discuss](https://groups.google.com/d/topic/elm-discuss/8Q2xwRh6UYc/discussion)
- [Recent talk](https://youtu.be/ar3TakwE8o0?t=528) by Richard Feldman (skip to 8:48)

**Comment by oliverbarnes** [comment]
I'll review this in the next few days, sorry for the delay.

**Comment by oliverbarnes** [comment]
re: webcomponents and polymer, thanks for the heads up - going to keep an eye on it. For now, I think we should just stick to `elm-mdl` and focus on getting through our milestones, as we discussed yesterday.

As for @tnum's feedback, she's not versed in Elm so it'll be hard for her to review locally. I've posted issue #59 so we can get a demo up somewhere and make it easy for her to see updates

**Comment by oliverbarnes** [comment]
About 

> Ideally, there should be no direct mentions of mdl-... classes in our view functions.

and

> The CSS code needs some clean up. Also, a CSS preprocessor may be worth considering.

Would you please elaborate?

About the first (`mdl-*` classes), I also don't like it much, but if it's a clunky dev experience to avoid them, I'd probably stick with them for the sake of speed of development

About the CSS preprocessor, I'd like to see some discussion on this before adding another dependency, I've had my share of pains with `sass` and `less` in rails apps...

**Comment by oliverbarnes** [comment]
by the way, would you please rebase this off of `master` - I'm not sold on `modd` and `devd` yet, and we should generally stick to PRs not being inter-dependendent.

**Comment by ThomasWeiser** [comment]
> by the way, would you please rebase this off of master - I'm not sold on modd and devd yet, and we should generally stick to PRs not being inter-dependendent.

Sure, I've rebased to master and amended the commits to use webpack.
More discussion about build system in #58.

**Comment by ThomasWeiser** [comment]
> About the first (`mdl-*` classes), I also don't like it much, but if it's a clunky dev experience to avoid them, I'd probably stick with them for the sake of speed of development
> 
> About the CSS preprocessor, I'd like to see some discussion on this before adding another dependency, I've had my share of pains with `sass` and `less` in rails apps...

I agree on both points.

At a later state when we have settled with certain `elm-mdl` styles it may be worth to refactor both the Elm code of the view functions and the CSS code. Should not be done prior to updating `elm-mdl` to version 8.x (together with Elm 0.18).

**Review by oliverbarnes — COMMENTED** [review]
Merging - we can deploy master, and after Teenum reviews styling, open another PR with fixes

**Pull request merged**
