### PR TITLE
Display author on proposal details

### PR DESCRIPTION
**Pull request by ThomasWeiser**
This depends on including the author on the payload from `GET /proposals/:id`.

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
Still WIP. It works, but code needs some touching up.

Data modelling currently looks like this:

``` elm
type alias Model =
  { ...
  , proposals : Dict String Proposal
  , participants : Dict String Participant
  }

type alias Proposal =
  { id : String
  , author : String
  , attr: ProposalAttr
  }

type alias ProposalAttr =
  { title : String
  , body : String
  }

type alias Participant =
  { id : String
  , attr: ParticipantAttr
  }

type alias ParticipantAttr =
  { name : String
  }
```

**Comment by ThomasWeiser** [comment]
Rebased on current master

**Comment by ThomasWeiser** [comment]
Finished, ready for your review.

As discussed, we should start to refactor and modularize the code.
Should go into separate issues/PRs.

**Comment by oliverbarnes** [comment]
This is a little game I know, but - do you think https://github.com/noahzgordon/elm-jsonapi might help  in anyway with the json-api decoding in general?

**Comment by oliverbarnes** [comment]
Went ahead and merged to get going, we can always add elm-jsonapi later

**Comment by oliverbarnes** [comment]
Ah, one thing I forgot to comment - maybe it's unavoidable, but there's something weird about `ProposalAttr` and `ParticipantAttr` types. To me at least. Feels like we're describing the json-api format... I'd much rather have a

```
type alias Proposal =
  { id : String
  , author : String
  , title : String
  , body : String
  }
```

But that might be old rails habits talking...

**Comment by ThomasWeiser** [comment]
I will definitely look into noahzgordon/elm-jsonapi.

As for the types `Proposal`/ `ProposalAttr`: This was an attempt to not repeat fieldsets.
I agree that this may not be the most beautiful solution here.

One simple alternative here would be:
- Rename `ProposalAttr` to `ProposalInput` and use it only for form input result.
- Define `Proposal` as a flat record, as you suggested.

The usage of noahzgordon/elm-jsonapi may also direct us to some specific type design here (not sure).

**Pull request merged**
