### PR TITLE
Update webpack configuration

### PR DESCRIPTION
**Pull request by ThomasWeiser**
Should use `webpack-dev-server` and hot reloading.

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
# webpack-dev-server

This webpack configuration uses standard webpack-dev-server and also enables hot reloading. Start webpack and the server with:

``` sh
> npm run dev
```

# optional: Colorized compiler messages

Elm compiler is able to produce helpfully colorized error messages. Unfortunately these colors won't make it through webpack and elm-webpack-loader. As a workaround we can optionally use modd alongside with webpack. A configuration file `modd.conf` is included in this PR.

With `modd` and `unbuffer` installed colorful compiler messages can be shown by running:

``` sh
> modd
```

Links to these tools:
- [`modd`](https://github.com/cortesi/modd)
- `unbuffer`, part of [Expect](https://www.nist.gov/services-resources/software/expect): [Linux](http://unix.stackexchange.com/a/25375), [OSX](http://apple.stackexchange.com/questions/193138/to-install-unbuffer-in-osx)

There is also an [open issue on elm-make](https://github.com/elm-lang/elm-make/issues/123) on the same topic.

**Comment by oliverbarnes** [comment]
Thanks @ThomasWeiser! Is this ready to merge or will you be adding some README notes? This comment above looks formatted, will it be its own wiki page?

**Comment by ThomasWeiser** [comment]
Ok, will add a note to README, just a moment.
Good idea to put detailed info into repo's wiki.

**Comment by ThomasWeiser** [comment]
Ok, please review my README changes.
Wiki entry not done yet.

Otherwise, the PR is ready to merge from my side.

**Comment by ThomasWeiser** [comment]
Created a preliminary wiki page. Linked in README

**Pull request merged**
