### PR TITLE
Continuous deployment

### PR DESCRIPTION
**Pull request by ThomasWeiser**
It'd be great to have the demo updated whenever `master` branch is updated on either repo, so it's always up to date.

@ThomasWeiser with the current setup, how hard would it be to implement this?

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
Added a `.travis.yml` configuration for CI/CD. What it does:
- Compile the Elm code
- Run Webpack to build dist.
- Push dist to a github repo to be served as gh-pages.

Deployment needs two env vars set in the corresponding Travis project: DEPLOY_REPO_SLUG and DEPLOY_REPO_KEY. See notes in `.travis.yml` for details.

**Comment by ThomasWeiser** [comment]
Things should be set up now.

- Travis is triggered on every push to any branch of the repo as well as any PR against the repo.
- Pushing to `master` will then deploy a successful build to [participateapp/participateapp.github.io](https://github.com/participateapp/participateapp.github.io)

Please note: The web-client needs some configuration about its base URL and the API endpoint to be used. These settings are currently hard-coded, see `Config.elm`. We have currently two possible configurations, one for local development and a second one for demo version at gh-pages and Heroku. With this PR we switch from the first one to the second one, so that the continuously-deployed demo is configured correctly. Later on we should move to a more flexible approach for configuration.

**Review by oliverbarnes — COMMENTED** [review]
👏

**Pull request merged**
