### PR TITLE
Supporting a proposal

### PR DESCRIPTION
**Pull request by ThomasWeiser**
```
As a participant
I want to support proposals by other participants
```

When viewing a proposal not his own, a participant sees a "Support this" button. When clicking on it, the button should change in some way to signify it's "on" somehow. Or maybe the proposal itself could have a visual cue that it's supported? 
- [ ] Define UX

### CODE REVIEW

**Comment by oliverbarnes** [comment]
- [x] handle "supported by me" scenario
- [x] handle "proposed by me" scenario (where current user then cannot suport her own proposal)

**Comment by ThomasWeiser** [comment]
Current state 7aa68e25e4b48a7ee53b61140d506aebaafd532f is the result of a pairing session with @oliverbarnes.

We agreed that the backend should indicate whether a proposal is supported by the current user. This `supported-by-me` flag should be an attribute of every proposal resource in a response. See https://github.com/oliverbarnes/participate-api/issues/27

(Edit: Didn't see you already mentioned "supported by me" above.)

**Comment by oliverbarnes** [comment]
`authored-by-me` and `supported-by-me` attributes added on https://github.com/oliverbarnes/participate-api/pull/30  and https://github.com/oliverbarnes/participate-api/pull/32

**Comment by ThomasWeiser** [comment]
Please review the PR.

Done:
- Decoding and storing `authored-by-me` and `supported-by-me`
- Use these flags to reflect the state on the support button
- Decode the response from `POST /support` and store the state in the model without reloading the proposal resource

API usage depends on oliverbarnes/participate-api#33

Will implement removing support (#24) afterwards as a separate PR.

**Comment by oliverbarnes** [comment]
Looks good. I didn't have time to test it yet, I'm assuming it was thoroughly tested before asking for the review? ;)

**Comment by ThomasWeiser** [comment]
Yes, I've tested it. Nonetheless, should soon start with automatic testing #49.

**Pull request merged**
