### PR TITLE
WIP listing proposals

### LINKED ISSUE #16: Viewing a list of proposals
```
As a participant
Once I log in
I want to see a list of present proposals
```

Below the `Create a proposal` link. I'm thinking a simple link list initially, but down the line a list of cards with title and a snippet from the proposal (or a new field, a summary), the whole card clickable and taking you to the project details view.

Need to start mocking up this stuff.

### PR DESCRIPTION
**Pull request by oliverbarnes**
Closes #16 

@ThomasWeiser I need a hand :)

I'm going towards a `ProposalList` type that's a `List Proposal` or a `List (Proposal, Participant)`. This will change how `proposals` is set in the model, and I'm also stuck with the following compiler error:

```
ERROR in ./src/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
-- TYPE MISMATCH ------------------------------------------------- ./src/Api.elm

The right argument of (|>) is causing a type mismatch.

236|   getProposalList id accessToken
237|>    |> Task.perform GettingProposalListFailed (uncurry GotProposalList)

(|>) is expecting the right argument to be a:

    Task Http.Error (List ( Proposal, Participant )) -> a

But the right argument is:

    Task Http.Error ( ProposalList, a ) -> Cmd Msg

Hint: I always figure out the type of the left argument first and if it is
acceptable on its own, I assume it is "correct" in subsequent checks. So the
problem may actually be in how the left and right arguments interact.

-- TYPE MISMATCH ------------------------------------------------- ./src/Api.elm

The argument to function `uncurry` is causing a mismatch.

237|                                                uncurry GotProposalList)
                                                            ^^^^^^^^^^^^^^^
Function `uncurry` is expecting the argument to be:

    ProposalList -> a -> b

But it is:

    ProposalList -> Msg
```

Maybe we can pair on this? Let me know when you got some time

### CODE REVIEW

**Comment by ThomasWeiser** [comment]
These commits should complete your work on that.

We currently just decode the `data` part of the response and replace `model.proposals` with the result.
Decoding and storing the `included` part of the response is not implemented yet.

On the `Home` route we view the received propopsal list (just title and link to its own route).

**Comment by oliverbarnes** [comment]
Good progress. Thanks for the update

**Comment by ThomasWeiser** [comment]
Rebased on current master

**Comment by ThomasWeiser** [comment]
Closed in favor of #54 

It is easier to reimplement these changes on top of current refactored master than to merge this branch in.

**Pull request closed without merging**
